public:
  pg_catalog:
    pg_ts_config:
      type: system_catalog
      schema:
        oid: int
        cfgname: varchar(64)
        cfgnamespace: int
        cfgowner: int
        cfgparser: int
      pg_types:
        oid: oid
        cfgname: name
        cfgnamespace: oid
        cfgowner: oid
        cfgparser: oid
      rows:
      - oid: 3748
        cfgname: simple
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12356
        cfgname: arabic
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12358
        cfgname: armenian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12360
        cfgname: basque
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12362
        cfgname: catalan
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12364
        cfgname: danish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12366
        cfgname: dutch
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12368
        cfgname: english
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12370
        cfgname: finnish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12372
        cfgname: french
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12374
        cfgname: german
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12376
        cfgname: greek
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12378
        cfgname: hindi
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12380
        cfgname: hungarian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12382
        cfgname: indonesian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12384
        cfgname: irish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12386
        cfgname: italian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12388
        cfgname: lithuanian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12390
        cfgname: nepali
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12392
        cfgname: norwegian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12394
        cfgname: portuguese
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12396
        cfgname: romanian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12398
        cfgname: russian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12400
        cfgname: serbian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12402
        cfgname: spanish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12404
        cfgname: swedish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12406
        cfgname: tamil
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12408
        cfgname: turkish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12410
        cfgname: yiddish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
