public:
  pg_catalog:
    pg_config:
      type: system_catalog
      schema:
        name: varchar(256)
        setting: varchar(256)
      pg_types:
        name: text
        setting: text
      rows:
      - name: BINDIR
        setting: /workspace/pg_catalog/postgres-17/bin
      - name: DOCDIR
        setting: /workspace/pg_catalog/postgres-17/share/doc
      - name: HTMLDIR
        setting: /workspace/pg_catalog/postgres-17/share/doc
      - name: INCLUDEDIR
        setting: /workspace/pg_catalog/postgres-17/include
      - name: PKGINCLUDEDIR
        setting: /workspace/pg_catalog/postgres-17/include
      - name: INCLUDEDIR-SERVER
        setting: /workspace/pg_catalog/postgres-17/include/server
      - name: LIBDIR
        setting: /workspace/pg_catalog/postgres-17/lib
      - name: PKGLIBDIR
        setting: /workspace/pg_catalog/postgres-17/lib
      - name: LOCALEDIR
        setting: /workspace/pg_catalog/postgres-17/share/locale
      - name: MANDIR
        setting: /workspace/pg_catalog/postgres-17/share/man
      - name: SHAREDIR
        setting: /workspace/pg_catalog/postgres-17/share
      - name: SYSCONFDIR
        setting: /workspace/pg_catalog/postgres-17/etc
      - name: PGXS
        setting: /workspace/pg_catalog/postgres-17/lib/pgxs/src/makefiles/pgxs.mk
      - name: CONFIGURE
        setting: ' ''--prefix'' ''/opt/postgresql'' ''--enable-integer-datetimes'' ''--enable-option-checking=fatal'' ''--with-gssapi'' ''--without-icu'' ''--without-ldap'' ''--with-libxml'' ''--with-libxslt'' ''--with-lz4'' ''--with-openssl'' ''--with-pgport=5432'' ''--with-python'' ''--with-readline'' ''--with-system-tzdata=/usr/share/zoneinfo'' ''--with-uuid=ossp'' ''--with-zstd'' ''LLVM_CONFIG=/usr/lib/llvm-16/bin/llvm-config'' ''CLANG=clang-16'''
      - name: CC
        setting: gcc
      - name: CPPFLAGS
        setting: -D_GNU_SOURCE -I/usr/include/libxml2
      - name: CFLAGS
        setting: -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2
      - name: CFLAGS_SL
        setting: -fPIC
      - name: LDFLAGS
        setting: -Wl,--as-needed -Wl,-rpath,'/opt/postgresql/lib',--enable-new-dtags
      - name: LDFLAGS_EX
        setting: ''
      - name: LDFLAGS_SL
        setting: ''
      - name: LIBS
        setting: '-lpgcommon -lpgport -lzstd -llz4 -lxslt -lxml2 -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm '
      - name: VERSION
        setting: PostgreSQL 17.4
